### DISCUSSION TITLE
rotate icons/pictures one day before collection

### DISCUSSION THREAD

**Discussion by NetRat88** [idaho/hassio-trash-card#503] [Ideas]
It would be great if you could rotate the icons or images one day before collection. Then you'll be immediately alerted. I had this in my TabletUI from FHEM and it would be a great development.

**Comment by NetRat88** [comment]
With some help in the home assistant forum I could find a solution.
The TrashCard provides the following CSS classes:

`.today.nextEvent / .today.futureEvent  / .tomorrow.nextEvent / .nextEvent  / .futureEvent  / .tomorrow.futureEvent`

Using the HACS integration card-mod (note version 3.4.4, as 3.5 is still buggy) I was able to rotate the icons one day before and on the day of pickup using the following code:

```yaml
card_mod:
  style: |
    .tomorrow .icon-container {
      animation: spin 4s linear infinite;
    }
    .today .icon-container {
      animation: spin 4s linear infinite;
    }
    @keyframes spin {
      100% {
        transform: rotate(360deg);
      }
    }
```

This is my current TrashCard configuration:

```yaml
event_grouping: true
drop_todayevents_from: "10:00:00"
next_days: 30
pattern:
  - icon: mdi:flower
    color: brown
    type: organic
    pattern: Biomüll
  - icon: mdi:newspaper
    color: blue
    type: paper
    pattern: Altpapier
  - icon: mdi:recycle-variant
    color: amber
    type: recycle
    pattern: Sack/Tonne gelb
  - icon: mdi:trash-can-outline
    color: grey
    type: waste
    pattern: Restmüll
  - icon: mdi:dump-truck
    color: purple
    type: others
  - label: Weihnachtsbaum
    icon: mdi:pine-tree
    color: green
    type: custom
    pattern: Weihnachtsbaum
day_style: counter
card_style: icon
alignment_style: center
color_mode: icon
items_per_row: 1
refresh_rate: 60
with_label: true
type: custom:trash-card
entities:
  - calendar.abfallkalender_mannheim
fill_container: true
icon_size: 70
card_mod:
  style: |
    .tomorrow .icon-container {
      animation: spin 4s linear infinite;
    }
    .today .icon-container {
      animation: spin 4s linear infinite;
    }
    @keyframes spin {
      100% {
        transform: rotate(360deg);
      }
    }
    :host .badge {
      #background-color: dodgerblue;
      #color: black;
      #font-weight: 700;
      #width: 50px;
      font-size: 1.5em;
      font-weight: bold; /* oder 700 */
    }
```

![2025-03-17_12-49-07 (1)](https://github.com/user-attachments/assets/f3e6c29a-f56b-4d5d-8712-84b39052c758)

Hope this helps!
NetRat88
