### ISSUE TITLE
Apply filtering to events before selecting event to display

### ISSUE THREAD

**Issue by kacperaniolek** [idaho/hassio-trash-card#110]
Hey,

I have tried Trash Card to work with my Google Calendar that contains only full-day events for waste schedule. Those are named after fractions, e.g. "Zmieszane" (mixed/general), "Plastiki" (plastic) etc. At first I had an impression that the card was intended to display multiple events, then I thought that maybe filters are applied to look for given items only.

For example, let's say my calendar has:
Mixed 18th December
Recycleable 19th December

If I configured the card for both mixed and recycleable, mixed would show. If I configured the card for recycleable (with `Recycleable` filter), only recycleable would show. So apparently the card basically shows the first found (the soonest) event and the styles it accordng to settings. Would it be possible to first filter the events, then select the first out of filtered ones, then apply the styling and display?

Example (full month view for reference):
![image](https://github.com/idaho/hassio-trash-card/assets/9115856/cabc0ec5-8f08-47bc-991b-86cf79d4f4fa)

Code:
```
      - type: horizontal-stack
        cards:
          - type: custom:trash-card
            entity: calendar.harmonogram_smieci
            settings:
              waste:
                label: Zmieszane
                icon: mdi:trash-can-outline
                pattern: Zmieszane
                color: grey
            fill_container: false
            next_days: 31
            full_size: false
            layout: horizontal
            view_layout:
              position: main
          - type: custom:trash-card
            entity: calendar.harmonogram_smieci
            settings:
              recycle:
                icon: mdi:recycle
                pattern: Plastik
                label: Plastiki i metale
                color: amber
            fill_container: false
            next_days: 31
            full_size: false
            layout: horizontal
            view_layout:
              position: main
      - type: custom:trash-card
        entity: calendar.harmonogram_smieci
        settings:
          others:
            icon: mdi:help-box
          paper:
            icon: mdi:note-multiple-outline
            label: Papier
            pattern: Papier
            color: blue
          waste:
            label: Zmieszane
            icon: mdi:trash-can-outline
            pattern: Zmieszane
            color: grey
          recycle:
            icon: mdi:recycle
            pattern: Plastik
            label: Plastiki i metale
            color: amber
          organic:
            label: Szkło
            icon: mdi:glass-fragile
            pattern: Szkło
            color: green
        fill_container: false
        next_days: 31
        full_size: false
        view_layout:
          position: main
        layout: horizontal
      - initial_view: dayGridMonth
        type: calendar
        entities:
          - calendar.harmonogram_smieci
```

I would expect the first card to show:
- on the left: "Zmieszane 18 grudnia"
- on the right: "Plastiki i metale 19 grudnia" - but it shows "Zmieszane" with default styling, as that card has no filter for "Zmieszane"

Do you think this is something doable or you don't see your work heading that direction?
