### ISSUE TITLE
Trash Card only show 1 Entry

### ISSUE THREAD

**Issue by MickLesk** [idaho/hassio-trash-card#118]
Hi,

ive an Problem, ive an "AbfallPlus" ics in my homeassistant. My Calendar works fine, but the trash card not. It only show "Trash" ("Restmüll"). Ive integrated another calendar plugin, so that all of them are displayed.

I have also "thrown away" my config once and adapted your example config.

I also set the days to 30 / 60 and then to 100 days as a test.

Comparison of the Trash plugin with a calendar plugin:
![image](https://github.com/idaho/hassio-trash-card/assets/47820557/ffafc1cb-4168-41ea-8e77-3171c31e6157)

here my config:
```
type: custom:trash-card
entity: calendar.abfallkalender
layout: vertical
settings:
  others:
    color: purple
    icon: mdi:trash-can
  organic:
    label: Bio
    icon: mdi:flower
    color: green
    pattern: Bio
  paper:
    label: Papier
    icon: mdi:newspaper-variant-multiple
    color: blue
    pattern: Blau
  recycle:
    label: Plaste
    icon: mdi:recycle-variant
    color: amber
    pattern: Gelb
  waste:
    label: Restmüll
    icon: mdi:trash-can-outline
    color: deep-orange
    pattern: Rest
next_days: 100

```

& here is an screenshot of my "Abfallkalender"
![image](https://github.com/idaho/hassio-trash-card/assets/47820557/2d0c6b29-128e-4eea-92ee-bf1614de9586)
