### ISSUE TITLE
[Bug]: All days event doesn't work anymore

### ISSUE THREAD

**Issue by maxyvon** [idaho/hassio-trash-card#143]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest TrashCard version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

If the next event in the calendar is an all-day event the card is empty.
![image](https://github.com/idaho/hassio-trash-card/assets/44422604/0b444452-d7c4-467f-9660-1dc9b0af0952)

### Expected Behavior

The card should display the next trash can day has it did in version 1.2.1.
I've tested with version 1.2.1 and it worked fine.
I tried with 1.2.1 because there seems to have been an update to add the possibility of having an event that doesn't last all day. on 1.2.2.
![image](https://github.com/idaho/hassio-trash-card/assets/44422604/1024992e-b425-420d-9e01-479cfc5e139d)

### Steps To Reproduce

I installed the latest version of the card. After trying to config the card I realised that it only worked on my calendars that didn't have an all-day event next.

### Environment

```markdown
- Browser: Chrome
- HA Version: 2023.12.3
- TrashCard: 1.4.1
```

**Comment by idaho** [comment]
@maxyvon hey, i have an idea why this happends, but not really sure.
Could you send me the response from the calender api for that Event. So i can have a look at it otherwise i will create a release which contains an option to debug it, and then i can have a closer look at this issue.

**Comment by Heisenberg9469** [comment]
same Problem here. Nothing works anymore :(

**Comment by Heisenberg9469** [comment]
![image](https://github.com/idaho/hassio-trash-card/assets/113998179/22576f8c-d360-4e46-b680-1291bba71c3b)

**Comment by maxyvon** [comment]
> @maxyvon hey, i have an idea why this happends, but not really sure. Could you send me the response from the calender api for that Event. So i can have a look at it otherwise i will create a release which contains an option to debug it, and then i can have a closer look at this issue.

I would but I don’t know how to do it..

**Comment by bertah** [comment]
Hi, let me chime in on this, since I also have the same problem.

Here is the response from the calendar API, captured via Chrome's developer console (Network tab). The first event is an all-day event, and is not getting picked up by the TrashCard.  The second event is getting displayed correctly.

```json
[
    {
        "start": {
            "date": "2023-12-28"
        },
        "end": {
            "date": "2023-12-29"
        },
        "summary": "Compost",
        "description": "Compost",
        "location": null,
        "uid": "6g1ttro59a53d493alup5eakk2@google.com",
        "recurrence_id": "6g1ttro59a53d493alup5eakk2_20231228T120000Z",
        "rrule": null
    },
    {
        "start": {
            "dateTime": "2023-12-29T07:00:00-05:00"
        },
        "end": {
            "dateTime": "2023-12-29T17:00:00-05:00"
        },
        "summary": "Recyclage",
        "description": null,
        "location": null,
        "uid": "4gagqd9a8plceorioo0ieksgcg@google.com",
        "recurrence_id": null,
        "rrule": null
    }
]
```

For reference, here is my TrashCard config:
```yaml
drop_todayevents_from: '10:00:00'
next_days: 4
day_style: default
type: custom:trash-card
entity: calendar.horaire_des_collectes_st_sulpice
settings:
  others: {}
  organic:
    label: Organic
    icon: mdi:flower
    pattern: Compost
  paper:
    label: Paper
    icon: mdi:newspaper
    pattern: Papier
  recycle:
    label: Recycle
    icon: mdi:recycle
    pattern: Recyclage
  waste:
    icon: mdi:trash-can
    label: Waste
    pattern: Déchets
```

And here is the visual output of the card:
![TrashCard](https://github.com/idaho/hassio-trash-card/assets/3036482/3932da61-3060-4962-824a-1d53f1f1ea54)

Let me know if you need anything else
