### ISSUE TITLE
[Bug]: Icons and color not work

### ISSUE THREAD

**Issue by Spawnsen** [idaho/hassio-trash-card#159]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest TrashCard version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Icons and color are not shown in the dashboard
![image](https://github.com/idaho/hassio-trash-card/assets/4910440/56b7777a-27fd-4de8-9b5b-da9d0b7786ec)

### Context

YAML state
```yaml
drop_todayevents_from: '10:00:00'
next_days: 14
settings:
  others: {}
  paper:
    label: Papier (Grüne Tonne)
    icon: mdi:newspaper-variant-multiple
    color: green
    pattern: (gruen)
  recycle:
    label: Plastik (Gelber Sack)
    icon: mdi:recycle-variant
    color: yellow
    pattern: (gelb)
  organic:
    label: Bioabfall (Braune Tonne)
    icon: mdi:flower
    color: brown
    pattern: (braun)
  waste:
    label: Restabfall (Graue Tonne)
    icon: mdi:trash-can-outline
    color: grey
    pattern: (grau)
type: custom:trash-card
entity: calendar.mullabfuhr
view_layout:
  position: main
fill_container: true
full_size: false
use_summary: false
layout: vertical
```

### Environment

```markdown
- Browser: Google Chrome (120)
- HA Version Core: 2024.1.1
- HA Version Supervisor: 2023.12.0
- HA Version Operating System: 11.3
- HA Version Frontend: 20240104.0
- TrashCard: 2.0.0-beta0
```
