### ISSUE TITLE
[Feature]: Add "bulk reject"

### ISSUE THREAD

**Issue by mdeweerd** [idaho/hassio-trash-card#161]
### Requirements

- [X] I have updated Mushroom to the latest available version
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Is your feature request related to a problem?

One of the collection types is "bulk reject" (or "Encombrants" in French).
I think that this could be a specific waste type rather than "other".

### Describe the solution you'd like

Add another waste type that would have the short name "bulk".

### Describe alternatives you've considered

The alternative is to have it covered by "other", but other could refer to other cases for instance for "dangerous waste".

**Comment by Arcane1980** [comment]
Can you not utilise the "Create New Pattern" and make a unique bulk trash for yourself?

I've used the function to add everything from my Dog's monthly Flea treatment to pay day and monthly bill due dates.
![Screenshot 2024-09-03 141644](https://github.com/user-attachments/assets/8870debd-eab1-451f-85c1-f3c4f8e569a2)

**Comment by mdeweerd** [comment]
Possibly when I set this up, pattern had some issues/it was not clear how to use it (I think I opened an issue for that and I expected pattern to be a regex).
The proposal is about having "common" trash classifications added to the default list.  That would avoid end users to have to add patterns.
For purposes that are not related to trash it is perfectly normal that you need to use patterns.

I currently use "other" as I have the following configuration based on a calendar.

```yaml
          - drop_todayevents_from: '10:00:00'
            next_days: 6
            day_style: default
            type: custom:trash-card
            entity: calendar.poubelles
            fill_container: true
            settings:
              recycle:
                label: Tri
                icon: mdi:recycle
                color: blue
                pattern: recycle
              others:
                color: purple
                icon: mdi:table-furniture
              waste:
                color: brown
                icon: mdi:trash-can-outline
                pattern: waste
                label: Ord.Ménagères
              organic:
                label: Vert
                icon: mdi:flower
                pattern: organic
              paper:
                label: Papier
                pattern: paper
                icon: mdi:newspaper-variant-multiple
            filter_events: false
            layout: horizontal
            use_summary: false
```
