### ISSUE TITLE
"day_style: counter" calculation wrong

### ISSUE THREAD

**Issue by mistergyle** [idaho/hassio-trash-card#224]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest TrashCard version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

the calculation of th counter in "day_Style" seems wrong. also "next_days" seems not to work correctly!?

today: 23.02.2024
next event "Restmüll": 26.02.2024

**TRY 1**
settings: 
day_style: counter
next_days: 3

result:
event doesn't show up? 

**TRY 2**
settings: 
day_style: counter
next_days: 4

result:
event shows up - label: "in 2 Tagen" > "in 2 days"

### Expected Behavior

settings: 
day_style: counter
next_days: 3

result:
event shows up - label: "in 3 Tagen"
because 23.02 + 3 days = 26.02

### Context

YAML state
```
drop_todayevents_from: '10:00:00'
next_days: 4
settings:
  others:
    color: purple
    icon: mdi:trash-can
  organic:
    label: Biomüll
    icon: mdi:flower
    color: green
    pattern: Bio
  paper:
    label: Altpapier
    icon: mdi:newspaper-variant-multiple
    color: blue
    pattern: Altpapier
  recycle:
    label: Gelber Sack
    icon: mdi:recycle-variant
    color: yellow
    pattern: Gelbe Säcke
  waste:
    label: Restmüll
    icon: mdi:trash-can-outline
    color: grey
    pattern: Rest
day_style: counter
type: custom:trash-card
entity: calendar.muellabfuhr
filter_events: true
fill_container: true
full_size: false
use_summary: false

```

### Environment

```markdown
- Browser:
- HA Version:
- TrashCard:
```
