### ISSUE TITLE
[Bug]: Inline --trash-card-background breaks card-mod

### ISSUE THREAD

**Issue by francis110** [idaho/hassio-trash-card#249]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest TrashCard version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

With the latest update I can no longer style the card with card-mod even using --trash-card-background.

### Expected Behavior

I would expect to be able to change be able to edit the card background in a way consistent with an overwhelming majority of cards  in HA.

### Steps To Reproduce

        ha-card {
          background: rgba(96, 125, 139,0.3);             
                    }
card-mod installed, injected this CSS

### Context

YAML state
```yaml
event_grouping: true
drop_todayevents_from: '10:00:00'
next_days: 4
pattern:
  - type: others
  - label: Recycle Pickup
    icon: mdi:recycle
    pattern: Recycle
    type: recycle
  - type: waste
items_per_row: 1
refresh_rate: 60
with_label: true
type: custom:trash-card
filter_events: true
entities:
  - calendar.disposal_management
card_mod:
  style: |
    ha-card {
      background: rgba(110, 255, 115,0.15);
      --card-primary-color: rgba(255, 255, 255,1);
      --card-primary-font-size: 18px;
      --card-secondary-color: rgba(255, 255, 255,0.7);
      --card-secondary-font-size: 12px;
      --card-secondary-line-height: 14px; 
                }
    mushroom-shape-icon {
       --shape-color-disabled: rgba(76, 175, 80,0.3);
       --icon-primary-color: rgba(255,255,255,.8);
                }
```

### Environment

```markdown
- Browser: Firefox, HA companion app on Pixel, (Chrome not rendering problem on windows)
- HA Version: 
   Core
    2024.3.0
   Supervisor
    2024.02.1
   Operating System
    12.0
- TrashCard:
```

### Anything else?

Clicking off the inline CSS using the inspect feature in Firefox on desktop renders the card-mod designation. I also tried changing the card-mod injection to --trash-card-background and --ha-card-background but neither worked so it seems the issue is how these browsers handle and prioritize the inline style at the html element.

**Comment by Bl4d3s** [comment]
Just a suggestion: 
Normally you can make your own styles more "important" than inline-styles with the !important flag.

e.g.
```css
ha-card {
    background: rgba(96, 125, 139,0.3) !important;             
}
```

Could be a workaround.
