### ISSUE TITLE
card only showing "others" card

### ISSUE THREAD

**Issue by jrhessels** [idaho/hassio-trash-card#256]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest TrashCard version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

default calander from my wast pickup service. looks like that the card search for specific message from the calender. and trash card it thinking that the other is active. 

![image](https://github.com/idaho/hassio-trash-card/assets/114057761/2cb5df11-cedf-4119-942f-088a3d6b07d2)

### Expected Behavior

expected to set the correct type 

### Context

event_grouping: true
drop_todayevents_from: '10:00:00'
next_days: 8
pattern:
  - icon: mdi:flower
    color: lime
    type: organic
  - icon: mdi:newspaper
    color: blue
    type: paper
  - icon: mdi:recycle-variant
    color: amber
    type: recycle
    label: Package waste pickup
  - icon: mdi:trash-can-outline
    color: grey
    type: waste
  - icon: mdi:dump-truck
    color: purple
    type: others
day_style: counter
card_style: chip
color_mode: background
items_per_row: 1
refresh_rate: 60
with_label: true
type: custom:trash-card
entities:
  - calendar.twente_milieu
layout: vertical
filter_events: false
use_summary: false
hide_time_range: false

### Environment

```markdown
- Browser:
- HA Version: 2024.3.0
- TrashCard: 2.0.0
```

**Comment by idaho** [comment]
Hey @jrhessels you need to add the pattern to the types. If i have a look at you configuration and you calendar entries the configuration should like
```yaml
event_grouping: true
drop_todayevents_from: '10:00:00'
next_days: 8
pattern:
  - icon: mdi:flower
    color: lime
    type: organic
    pattern: organic
  - icon: mdi:newspaper
    color: blue
    type: paper
  - icon: mdi:recycle-variant
    color: amber
    type: recycle
    label: Package waste pickup
    pattern: packages
  - icon: mdi:trash-can-outline
    color: grey
    type: waste
  - icon: mdi:dump-truck
    color: purple
    type: others
day_style: counter
card_style: chip
color_mode: background
items_per_row: 1
refresh_rate: 60
with_label: true
type: custom:trash-card
entities:
  - calendar.twente_milieu
layout: vertical
filter_events: false
use_summary: false
hide_time_range: false
```

 Have a look at the organic or the recycle type settings
