### ISSUE TITLE
[Bug]: Days in the future issue

### ISSUE THREAD

**Issue by Kevin-Kusters** [idaho/hassio-trash-card#274]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest TrashCard version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Hi,

I have installed this great card but for some reason the days in the future option doesn't work as intended. 
I have set the days in the future to 1 but it shows a calendar event that is 2 days in the future. (See attached screenshot).

Yesterday it was Wednesday 27-3 and the garbage pick up event is on Saturday 30-3. But the card was already visible on the 27th while the days in the future is set to 1.

Any idea how to solve this?
![Schermafbeelding 2024-03-28 om 12 14 43](https://github.com/idaho/hassio-trash-card/assets/51093690/0426956d-b684-4b4e-a1c3-dfdf1cb56677)

### Expected Behavior

Be hidden until 1 day before the pickup (calendar event)

### Context

YAML state
```
type: custom:trash-card
entities:
  - calendar.afvalbeheer_rd4
items_per_row: 1
refresh_rate: 60
with_label: true
filter_events: true
hide_time_range: false
full_size: false
use_summary: false
event_grouping: true
drop_todayevents_from: '10:00:00'
next_days: 1
pattern:
  - icon: mdi:delete-empty
    color: light-green
    type: organic
    label: Huisvuilophaling GFT
    pattern: GFT
  - icon: mdi:delete-empty
    color: light-green
    type: paper
    pattern: Papier
    label: Huisvuilophaling papier
  - icon: mdi:delete-empty
    color: light-green
    type: recycle
    label: ' Huisvuilophaling PMD'
    pattern: PMD
  - icon: mdi:delete-empty
    color: light-green
    type: waste
    label: Huisvuilophaling restafval
    pattern: Restafval
  - icon: mdi:dump-truck
    color: purple
    type: others


```

### Environment

```markdown
- Browser: Safari, Chrome and HA companion app on iOS and Android
- HA version: 
Core 2024.3.3
Supervisor 2024.03.1
Operating System 12.1
Frontend 20240307.0
- TrashCard: 2.1.0
```
