### ISSUE TITLE
Small help needed

### ISSUE THREAD

**Issue by asemev** [idaho/hassio-trash-card#309]
Hello, I would like to do exactly this:
![image](https://github.com/idaho/hassio-trash-card/assets/30929896/8d91f0e8-dd50-42fc-8cde-d38f6e82b93c)
Could you please show me the YAML code?
Many thanks!

**Comment by idaho** [comment]
Hey @asemev you need to download some images for the pictures and store them in the `www/` folder on your homeassistant installation.

The YAML code is then 

```yaml
event_grouping: true
drop_todayevents_from: '10:00:00'
next_days: 300
pattern:
  - label: Organic
    icon: mdi:flower
    pattern: BrAun
    color: brown
    type: organic
    picture: /local/braunetonne.png
  - label: Paper
    icon: mdi:newspaper-variant-multiple-outline
    color: indigo
    pattern: (blau)
    type: paper
    picture: /local/blauetonne.png
  - label: Recycling
    pattern: gelb
    icon: mdi:recycle-variant
    color: amber
    type: recycle
    picture: /local/gelbetonne.png
  - pattern: (grau)
    icon: mdi:trash-can
    label: Waste
    color: black
    type: waste
    picture: /local/schwarzetonne.png
  - icon: mdi:dump-truck
    color: purple
    type: others
day_style: counter
alignment_style: left
items_per_row: 4
refresh_rate: 60
with_label: true
type: custom:trash-card
fill_container: false
full_size: false
filter_events: true
use_summary: false
hide_time_range: false
debug: false
layout: vertical
icon_size: 95
entities:
  - >
```
