### ISSUE TITLE
[Bug]: Card Style does not show labels

### ISSUE THREAD

**Issue by csigritz** [idaho/hassio-trash-card#322]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest TrashCard version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Currently when using `card_style: card` there are no labels shown. When using `card_style: chip` everything looks fine.

![CleanShot 2024-05-31 at 17 37 16@2x](https://github.com/idaho/hassio-trash-card/assets/956016/d3a14786-a866-450c-a845-7ee88ce27977)
![CleanShot 2024-05-31 at 17 38 41@2x](https://github.com/idaho/hassio-trash-card/assets/956016/21993409-702f-46b0-98c8-5a4f4d3b70e7)

Also when inspecting the card via dev tools, there is no label or text. within the element.

### Expected Behavior

Labels should also appear when using the `card_style: card`

### Steps To Reproduce

1. Install Addon
2. Configure addon with type card
3. Labels do not appear

### Context

YAML state
```yaml
event_grouping: true
drop_todayevents_from: '10:00:00'
next_days: 30
pattern:
  - icon: mdi:flower
    color: lime
    type: organic
    pattern: Biotonne
    label: Biotonne
  - icon: mdi:newspaper
    color: blue
    type: paper
    pattern: Papiertonne
    label: Papier
  - icon: mdi:recycle-variant
    color: amber
    type: recycle
    pattern: Gelber Sack
    label: Gelber Sack
  - icon: mdi:trash-can-outline
    color: grey
    type: waste
    pattern: Restmüll
    label: Restmüll
  - icon: mdi:dump-truck
    color: purple
    type: others
  - label: Sperrmüll
    icon: mdi:dump-truck
    color: cyan
    type: custom
    pattern: Sperrmüll
day_style: counter
card_style: card
alignment_style: space
color_mode: icon
items_per_row: 3
refresh_rate: 60
with_label: true
type: custom:trash-card
entities:
  - calendar.trash_cal
filter_events: true
use_summary: false
hide_time_range: true
full_size: true
```

### Environment

```markdown
- Browser: Chrome, Safari, Arc
- HA Version: 2024.5.5
- HACS: 1.34.0
- TrashCard: 2.2.1
- Theme: Default
```
