### ISSUE TITLE
Card is blank

### ISSUE THREAD

**Issue by pugshot** [idaho/hassio-trash-card#342]
I've installed mushroom.
I've added weekly all day events called Trash to my local calendar.
I've installed Trash Card and added the js resource.
I've added a custom Trash Card, and modified Waste instance to follow a pattern called Trash. I've added an entity for the calendar.

I have no idea what to do next, the instructions don't continue from here. All I get from this is a blank card with nothing on it. Why did I download Mushroom? How am I utilizing it if I'm not selecting a Mushroom card? Maybe I'm stupid, but without full instructions I can't seem to make this work.

**Comment by rjpearce** [comment]
I couldn't get it to work adding a new custom Trash card either.

@pugshot  Try adding a 'Manual' card you can then specify it as YAML which worked for me in the end.

**Comment by raptile** [comment]
On my side:
```
entities:
  - person.<person_name>
  - calendar.vuilnis
```
  I had to remove the person entity to get it working.

**Comment by veedubb65** [comment]
My card is blank as well. 

Here is the yaml:

```
event_grouping: true
drop_todayevents_from: '10:00:00'
next_days: 14
pattern:
  - icon: mdi:flower
    color: lime
    type: organic
    label: Yard
    pattern: yard
  - icon: mdi:newspaper
    color: blue
    type: paper
  - icon: mdi:recycle-variant
    color: blue
    type: recycle
    label: Recycle
    pattern: waste
  - icon: mdi:trash-can-outline
    color: dark-grey
    type: waste
    label: Garbage
    pattern: waste
  - icon: mdi:dump-truck
    color: purple
    type: others
day_style: default
day_style_format: yyyy.MM.dd
card_style: icon
alignment_style: left
color_mode: background
items_per_row: 1
refresh_rate: 5
with_label: true
type: custom:trash-card
entities:
  - calendar.trash
filter_events: false
```
