### ISSUE TITLE
All colors change when you change other tab

### ISSUE THREAD

**Issue by TechNerd010** [idaho/hassio-trash-card#373]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest TrashCard version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

As soon as I change the tab other all colors are changed I do not have yellow for organic waste or brown for residual waste
![Screenshot_20240813_024630_Home Assistant](https://github.com/user-attachments/assets/a8d453bd-a98d-4585-bdb7-dabea0949700)
![Screenshot_20240813_024625_Home Assistant](https://github.com/user-attachments/assets/4f2ca244-9f40-44d5-a669-619b3344d221)
![Screenshot_20240813_024605_Home Assistant](https://github.com/user-attachments/assets/ae6d39f1-63fb-4559-ae81-42bfa1888871)

### Context

YAML state
```
event_grouping: false
drop_todayevents_from: '15:00:00'
next_days: 15
pattern:
  - icon: mdi:flower
    color: lime
    type: organic
    label: 'Biotonne '
  - icon: mdi:newspaper
    color: blue
    type: paper
    label: 'Papiertonne '
  - icon: mdi:recycle-variant
    color: amber
    type: recycle
  - icon: mdi:trash-can-outline
    color: grey
    type: waste
    label: 'Restmülltonne '
  - icon: mdi:dump-truck
    color: purple
    type: others
day_style: counter
alignment_style: left
color_mode: icon
items_per_row: 1
refresh_rate: 300
with_label: true
type: custom:trash-card
entities:
  - calendar.ics
filter_events: false
use_summary: false
full_size: false
layout: horizontal


```

### Environment

```markdown
- Browser: home assistant app
- HA Version: latest
- TrashCard: latest
```

### Anything else?

Since this is my first bug report, please forgive me if I forgot something
