### ISSUE TITLE
Assistance - Pictures instead of icons

### ISSUE THREAD

**Issue by Roving-Ronin** [idaho/hassio-trash-card#430]
In the examples it mentions using pictures instead of icons and shows an example with wheelie bins:

![image](https://github.com/user-attachments/assets/92a7ee07-24e1-4331-a733-2cb749c4bd88)

or like this (needing Red, Green and Yellow tops): 
![image](https://github.com/user-attachments/assets/62b5a0fa-8c4a-452f-b725-21577742a24f)

Are these wheelie bin type pictures available to download? If so, from where ?

Thanks in Advance.

**Comment by theitghost** [comment]
If i want use a big picture, they have all only a small Icon format. Can not change the size.

**Comment by barthel-eu** [comment]
I have the same problem that the "picture" is showing only in default icon size. `icon_size:200` does not change anything. It would be _**very**_ helpful to have a code example how to set up like in the example of the wheeled trash can.
Aside, it _**is**_ in a horizontal layout but `fill_container: true` does not result in a fill of the area either, nor can I make it show a background, would likely need to do that on the image? PEBKAS? Or "feature"?
```
event_grouping: true
drop_todayevents_from: "10:00:00"
next_days: 3
icon_size: 100
fill_container: true
full_size: true
pattern:
  - icon: mdi:leaf-circle-outline
    color: green
    type: organic
    pattern: Grüne Tonne
    picture: /local/images/trashcan-green.png
  - icon: mdi:newspaper
    color: blue
    type: paper
  - icon: mdi:recycle
    color: amber
    type: recycle
    pattern: Wertstofftonne
    picture: /local/images/trashcan-yellow2.png
  - icon: mdi:trash-can-outline
    color: grey
    type: waste
    pattern: Graue Tonne
    picture: /local/images/trashcan-black.png
  - icon: mdi:dump-truck
    color: purple
    type: others
day_style: weekday
card_style: icon
alignment_style: left
color_mode: icon
items_per_row: 1
refresh_rate: 60
with_label: true
type: custom:trash-card
entities:
  - calendar.apps_by_abfall
use_summary: false

```
I tried changing "icon" also to the picture:
```
  - icon: /local/images/trashcan-green.png
    color: green
    type: organic
    pattern: Grüne Tonne
    picture: /local/images/trashcan-green.png
```
Or remove the line icon:
No change (background is a NASA image, next to the trash card is a gauge in default size). Whatever I do, the trash card doesn't change the icon size:
![tmp](https://github.com/user-attachments/assets/dcb5cd27-c352-458c-ba39-dd4a5a2e67e4)
