### ISSUE TITLE
[Bug]: After updating to latest version integration breaks

### ISSUE THREAD

**Issue by ChirpyTurnip** [idaho/hassio-trash-card#431]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest TrashCard version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

All trash entried fail to work. System returns these erros:

No entites defined - Please select at least one calendar entity to get TrashCard to work.

And 

At path: entity -- Expected a value of type `never`, but received: `"calendar.rubbish_collection"`

### Expected Behavior

Existing configuration just works...

### Steps To Reproduce

Upgrade to latest version
Refresh
Everything broken

(for me at least)

Reverting back tot he previous version everything works again as expected.

### Context

YAML state
```
type: vertical-stack
cards:
  - event_grouping: true
    drop_todayevents_from: "10:00:00"
    next_days: 3
    pattern:
      - type: others
      - label: General Waste
        icon: mdi:trash-can
        color: red
        pattern: General Waste
        type: organic
    day_style: counter
    alignment_style: left
    items_per_row: 1
    refresh_rate: 60
    with_label: true
    type: custom:trash-card
    filter_events: true
    use_summary: true
    entities:
      - calendar.rubbish_collection
  - drop_todayevents_from: "10:00:00"
    next_days: 3
    day_style: counter
    type: custom:trash-card
    entity: calendar.rubbish_collection
    settings:
      others: {}
      organic:
        label: General Recycling
        icon: mdi:recycle-variant
        color: blue
        pattern: General Recycling
    filter_events: true
    use_summary: true
  - drop_todayevents_from: "10:00:00"
    next_days: 3
    day_style: counter
    type: custom:trash-card
    entity: calendar.rubbish_collection
    settings:
      others: {}
      organic:
        label: Glass Recycling
        icon: mdi:bottle-wine
        color: yellow
        pattern: Glass Recycling
    filter_events: true
    use_summary: true
  - drop_todayevents_from: "10:00:00"
    next_days: 3
    day_style: counter
    type: custom:trash-card
    entity: calendar.rubbish_collection
    settings:
      others: {}
      organic:
        label: Green Waste
        icon: mdi:leaf
        color: green
        pattern: Green Waste
    filter_events: true
    use_summary: true

```

### Environment

```markdown
- Browser: Chrome
- HA Version:2024.10.1
- TrashCard: 2.4 (Latest)
```

**Comment by idaho** [comment]
@ChirpyTurnip thats not a bug. Please read the README and check your configuration. Since version 2.0.0 the card is supporting multiple entities instead of a single one. Till the last version, the entity configuration parameter was deprecated and now dropped.

Change your code to the following and it should work again or open the visual editor

```yaml
type: vertical-stack
cards:
  - event_grouping: true
    drop_todayevents_from: "10:00:00"
    next_days: 3
    pattern:
      - type: others
      - label: General Waste
        icon: mdi:trash-can
        color: red
        pattern: General Waste
        type: organic
    day_style: counter
    alignment_style: left
    items_per_row: 1
    refresh_rate: 60
    with_label: true
    type: custom:trash-card
    filter_events: true
    use_summary: true
    entities:
      - calendar.rubbish_collection
  - drop_todayevents_from: "10:00:00"
    next_days: 3
    day_style: counter
    type: custom:trash-card
    entities:
      - calendar.rubbish_collection
    settings:
      others: {}
      organic:
        label: General Recycling
        icon: mdi:recycle-variant
        color: blue
        pattern: General Recycling
    filter_events: true
    use_summary: true
  - drop_todayevents_from: "10:00:00"
    next_days: 3
    day_style: counter
    type: custom:trash-card
    entities:
      - calendar.rubbish_collection
    settings:
      others: {}
      organic:
        label: Glass Recycling
        icon: mdi:bottle-wine
        color: yellow
        pattern: Glass Recycling
    filter_events: true
    use_summary: true
  - drop_todayevents_from: "10:00:00"
    next_days: 3
    day_style: counter
    type: custom:trash-card
    entities:
      - calendar.rubbish_collection
    settings:
      others: {}
      organic:
        label: Green Waste
        icon: mdi:leaf
        color: green
        pattern: Green Waste
    filter_events: true
    use_summary: true
```
