### ISSUE TITLE
[Bug]: Filtering does not work correctly within HA mobile app

### ISSUE THREAD

**Issue by Ben-Bitdiddle-DE** [idaho/hassio-trash-card#445]
### Requirements

- [X] I checked the troubleshooting section in the README to verify that I have the latest TrashCard version.
- [X] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

First of all, thanks for implementing #393.

I today gave it a try and observed, that on my mobile devices (iOS and/or android) the filtering is somewhat different from the desktop/browser. It seems, as far as i can reproduce it, that location filtering does not get involved on the mobile devices (or filtering at all).

Result on desktop:
![result_desktop](https://github.com/user-attachments/assets/b1c94527-38b9-485a-8094-a6e133864931)

Result on mobile:
![IMG_2582](https://github.com/user-attachments/assets/1510d879-a9e4-49f3-81ee-678bbb372da0)

i configured here a dayahead of 30 days just to find out which entries aren't filtered. The entries which are not "full day" (7:00 to 7:00) are the ones where i filtered location. 

Oddly enough, even if a configure the "full day only" option, these events also aren't filtered out.

Oddly#2: Looking at it as i'm writing, i also observe a time difference of one day im some (not all!) entries. Have look at "Gelber Sack" as of 10/28, which ist shown as 10/27 in the mobile app (10/28 is the correct date). Also hold for "Restmülltone" 11/05, where 11/06 is on desktop (and which is right). I am not sure if the wrong dates also come from the TrashCard integration for visualisation.

### Steps To Reproduce

event_grouping: false
drop_todayevents_from: '10:00:00'
next_days: 30
pattern:
  - icon: mdi:biohazard
    color: purple
    type: organic
    pattern: Schadstoff
    label: Schadstoffmobil
    pattern_exact: false
  - icon: mdi:newspaper
    color: green
    type: paper
    pattern: Papiertonne
    pattern_exact: false
  - icon: mdi:recycle-variant
    color: amber
    type: recycle
    pattern: Sack
    pattern_exact: false
  - icon: mdi:trash-can-outline
    color: grey
    type: waste
    pattern: Restmüll
    pattern_exact: false
  - icon: mdi:dump-truck
    color: purple
    type: others
alignment_style: left
items_per_row: 1
refresh_rate: 60
with_label: true
type: custom:trash-card
entities:
  - calendar.own_house
filter_events: true
only_all_day_events: true
location: höchsten

### Environment

```markdown
- Browser: Brave 1.68.134, Edge 129.0.2792.89
- HA Version: 2024.7.3
- TrashCard: 2.4.2
- iOS App: 2024.9.4 (2024.905)
- Adroid App: 2024.9.4-full
```

**Comment by Ben-Bitdiddle-DE** [comment]
```
event_grouping: false
drop_todayevents_from: '10:00:00'
next_days: 30
pattern:
  - icon: mdi:biohazard
    color: purple
    type: organic
    pattern: Schadstoff
    label: Schadstoffmobil
    pattern_exact: false
  - icon: mdi:newspaper
    color: green
    type: paper
    pattern: Papiertonne
    pattern_exact: false
  - icon: mdi:recycle-variant
    color: amber
    type: recycle
    pattern: Sack
    pattern_exact: false
  - icon: mdi:trash-can-outline
    color: grey
    type: waste
    pattern: Restmüll
    pattern_exact: false
  - icon: mdi:dump-truck
    color: purple
    type: others
alignment_style: left
items_per_row: 1
refresh_rate: 60
with_label: true
type: custom:trash-card
entities:
  - calendar.own_house
filter_events: true
only_all_day_events: true
location: höchsten
```
