### ISSUE TITLE
[Bug]: Trascard not available on certain device

### ISSUE THREAD

**Issue by Isengo1989** [idaho/hassio-trash-card#532]
### Requirements

- [x] I checked the troubleshooting section in the README to verify that I have the latest TrashCard version.
- [x] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Card does not show on Shelly Wall Display but any other browser with the same user.

### Expected Behavior

Show card

### Steps To Reproduce

1. Create card
2. Check card on mobile and desktop
3. Check card on Shelly Wall Display

### Context

YAML state
```yaml
event_grouping: true
drop_todayevents_from: "10:00:00"
next_days: 4
pattern:
  - icon: mdi:flower
    color: green
    type: organic
    pattern: Biotonne
  - icon: mdi:newspaper
    color: blue
    type: paper
    pattern: Altpapier
  - icon: mdi:recycle-variant
    color: amber
    type: Biotonne
  - icon: mdi:trash-can-outline
    color: grey
    type: waste
    label: Restmüll
    pattern: Restmüll
  - icon: mdi:dump-truck
    color: purple
    type: others
  - label: Gelber Sack
    icon: mdi:calendar
    color: yellow
    type: custom
    pattern: Gelbe
day_style: counter
alignment_style: left
items_per_row: 1
refresh_rate: 60
with_label: true
type: custom:trash-card
entities:
  - calendar.mull_2025

```

### Environment

```markdown
- Browser:Version 132.0.6834.110 (Offizieller Build) (64-Bit)
- HA Version:2025.1.4 
- TrashCard: 2.4.5
```

### Debug data

```json

```

### Anything else?

![Image](https://github.com/user-attachments/assets/5bf6ce07-ef43-4c6e-b24b-eac745221263)
![Image](https://github.com/user-attachments/assets/2e25ee16-57fe-4697-a152-7ca902e43eb4)
