### ISSUE TITLE
[Bug]: Cant change border and background

### ISSUE THREAD

**Issue by jkaberg** [idaho/hassio-trash-card#558]
### Requirements

- [x] I checked the troubleshooting section in the README to verify that I have the latest TrashCard version.
- [x] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Im trying to make the trash card more inline with my other cards, however it doesn't seem like trash card uses the default variables?

![Image](https://github.com/user-attachments/assets/f683a740-f824-4cca-b9b4-534e411cf840)

### Expected Behavior

When overriding border-width and background using card-mod I'd expect it to change the color, layout etc.

### Context

YAML state
```yaml
event_grouping: true
drop_todayevents_from: "10:00:00"
next_days: 30
pattern:
  - label: Matavfall
    icon: mdi:flower
    pattern: matavfall
    color: light-green
    type: organic
  - label: Papp og papir
    icon: mdi:newspaper-variant-multiple-outline
    color: indigo
    pattern: papp
    type: paper
  - label: Plastemballasje
    pattern: Plastemballasje
    icon: mdi:recycle-variant
    color: amber
    type: recycle
  - pattern: Restavfall
    icon: mdi:trash-can
    label: Restavfall
    color: dark-grey
    type: waste
  - label: Glass- og metallemballasje
    icon: mdi:electron-framework
    color: pink
    type: custom
    pattern: metallembalasje
  - icon: mdi:dump-truck
    color: purple
    type: others
day_style: counter
alignment_style: left
color_mode: icon
items_per_row: 1
refresh_rate: 60
with_label: true
layout: horizontal
type: custom:trash-card
entities:
  - calendar.tommeplan
filter_events: true
use_summary: false
hide_time_range: true
grid_options:
  columns: full
full_size: true
card_mod:
  style: |
    ha-card {
       border-width: 0px !important;
       background: none !important;
    }

```

### Environment

```markdown
- Browser:
- HA Version:
- TrashCard:
```

### Debug data

```json

```
