### ISSUE TITLE
[Bug]: Icons missing in standard / card view

### ISSUE THREAD

**Issue by xkelement** [idaho/hassio-trash-card#564]
### Requirements

- [x] I checked the troubleshooting section in the README to verify that I have the latest TrashCard version.
- [x] I did a search to see if there is a similar issue or if a pull request is open.

### Current Behavior

Hello, I have icons missing in standard / card view.

![Image](https://github.com/user-attachments/assets/a6af6085-6c14-4127-8e27-a557710a5936)

In other card styles (chip o icon) icons are working normally.

### Expected Behavior

I assume that standard card style should look like one from examples.

![Image](https://github.com/user-attachments/assets/09eeca02-69ce-4612-8a2f-e580fd1fa56b)

### Context

YAML state
```yaml
event_grouping: true
drop_todayevents_from: "10:00:00"
next_days: 15
pattern:
  - icon: mdi:flower
    color: brown
    type: organic
    label: BIO Odpad
    pattern: BIO odpad
  - icon: mdi:newspaper
    color: blue
    type: paper
    label: Papier
    pattern: Papier
  - icon: mdi:recycle-variant
    color: amber
    type: recycle
    label: Plasty
    pattern: Plasty
  - icon: mdi:trash-can-outline
    color: grey
    type: waste
    label: Komunál
    pattern: Komunál
  - icon: mdi:dump-truck
    color: purple
    type: others
alignment_style: left
items_per_row: 1
refresh_rate: 60
with_label: true
icon_size: 120
type: custom:trash-card
entities:
  - calendar.odpad_2025
```

### Environment

```markdown
- Browser: Chrome 134.0.6998.178 / iOS Safari
- HA Version: 2025.1.2
- TrashCard: v2.4.7
```

### Debug data

```json

```
