### ISSUE TITLE
Wrong color?

### ISSUE THREAD

**Issue by Framstag** [idaho/hassio-trash-card#84]
Besides the sizing problem, I would also have expected another color from the configuration.

![grafik](https://github.com/idaho/hassio-trash-card/assets/14061582/0036d1a9-01c5-4e60-92f9-6d536f0d0766)

Configuration:
```
type: custom:trash-card
entity: calendar.ics
settings:
  others: {}
  recycle:
    label: Wertstoffsammlung
    pattern: (Wertstoffsammlung)
    icon: mdi:recycle-variant
    color: yellow
  waste:
    label: Restabfallsammlung
    pattern: (Restabfallsammlung)
    icon: mdi:trash-can-outline
    color: grey
  paper:
    pattern: (Papiersammlung)
    label: Papiersammlung
    icon: mdi:newspaper-variant-multiple
    color: blue
fill_container: false
layout: horizontal
```

Where is the yellow? I would have expected an all yellow button background?
